import Header from "@/components/Header";
import "./globals.css";
import { Provider } from "./provider";
import { getServerSession } from "next-auth/next";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className="">
        <Provider session={session}>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
